import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import SmallCard from "@/components/SmallCard";
import loadSmallPictures from "@/lib/loadSmallPictures";
import loadMediumPictures from "@/lib/laodMediumPictures";
import MediumCard from "@/components/MediumCard";
import LargeCard from "@/components/LargeCard";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ exploreData, cardsData }) {
  return (
    <>
      <Head>
        <title>Airbnb 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        {/* Small Cards Section */}
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => {
              return (
                <SmallCard
                  key={img}
                  location={location}
                  distance={distance}
                  img={img}
                />
              );
            })}
          </div>
        </section>

        {/* Medium Cards Section */}
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map(({ img, title }) => {
              return <MediumCard key={title} img={img} title={title} />;
            })}
          </div>
        </section>

        {/* Large Card Section */}
        <section className="relative py-16 cursor-pointer">
          <LargeCard
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlists curated by Airbnb"
            buttonText="Get Inspired"
          />
        </section>
      </main>

      
      <Footer />
     
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await loadSmallPictures();
  const cardsData = await loadMediumPictures();
  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
